/*
	Everything the engine loads by path goes through here. On this console
	the files ride inside the executable: the build embeds whatever the
	game leaves under its filesystem/ directory, and a path such as
	"rom:/models/room.model" is looked up in that table. A CD-ROM loader
	takes the same paths later; nothing above this module changes.

	The owner keeps the pointer it was handed, the way an entity keeps its
	mesh, and gives it back when it dies.
*/
#ifndef ENGINE_32_RESOURCE_H
#define ENGINE_32_RESOURCE_H

#include <stdint.h>
#include <stddef.h>


/* One embedded file. The table is generated by the build. */
struct EmbeddedFile
{
	const char    *path;
	const uint8_t *start;
	const uint8_t *end;
};

extern const EmbeddedFile embedded_file[];
extern const unsigned     embedded_file_count;


class Resource
{
public:

	/* The bytes of a path, or null when there is no such file. The data
	   is read only and never goes away, so there is nothing to give back
	   for the raw file itself; the typed loaders above this keep their own
	   counts. */
	static const uint8_t *find(const char *path, size_t *size);
};


#endif
